[build]
  command = "npm install && npm run build"
  functions = "functions"

[functions]
  included_files = ["folder-static/*","*"]

[[redirects]]
  from = "/tugas/*"
  to = "/.netlify/functions/content/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/.netlify/functions/home/:splat"
  status = 200
  force = true

[[redirects]]
from = "/*"
to = "/www/404.html"
status = 404
force = true
