[build]
  command = "npm install && npm run build"
  functions = "functions"

[functions]
  included_files = ["folder-static/*","*"]

[[redirects]]
  from = "/tugas/*"
  to = "/.netlify/functions/core/:splat"
  status = 200
  force = true
